package xiroc.beneficium;

import java.io.File;
import java.util.logging.LogManager;
import java.util.logging.Logger;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;
import xiroc.beneficium.item.ItemTalismanOfTheBenefactor;
import xiroc.beneficium.util.CreativeTabBeneficium;
import xiroc.beneficium.util.EventManager;

@Mod(modid = "beneficium", name = "Beneficium", version = "alpha", acceptedMinecraftVersions = "1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9")
public class Beneficium {

	public static final Logger logger = Logger.getLogger("Beneficium");

	public static double XP_MULTIPLIER = 2.0D;
	public static double XP_MULTIPLIER_DIVINE = 6.0D;

	public static final CreativeTabBeneficium tabBeneficium = new CreativeTabBeneficium();

	public static final Item talismanOfTheBenefactor = new ItemTalismanOfTheBenefactor();

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.name = EnumChatFormatting.GOLD + "Beneficium";
		data.authorList.add("XIROC");
		data.version = "0.1.1";
		data.logoFile = "assets/beneficium/textures/logo/logo.png";
		
		MinecraftForge.EVENT_BUS.register(new EventManager());
		
		GameRegistry.registerItem(talismanOfTheBenefactor, "talisman");
		GameRegistry.addRecipe(new ItemStack(talismanOfTheBenefactor), "gdg", "dbd", "gdg", 'g', Items.gold_ingot, 'd',
				Items.diamond, 'b', Items.emerald);
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new EventManager());
	}

}
